// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC90n3exnwdEL7dIMqsivmUBkYGB16x94k',
    appId: '1:660366217495:web:7845d32658e233acef6752',
    messagingSenderId: '660366217495',
    projectId: 'fir-flutter-83655',
    authDomain: 'fir-flutter-83655.firebaseapp.com',
    storageBucket: 'fir-flutter-83655.appspot.com',
    measurementId: 'G-NVT4DG3C0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAG5dei8tAO92xhGfqK19RbZKbH3kgFtY',
    appId: '1:660366217495:android:263251ea9ce9d550ef6752',
    messagingSenderId: '660366217495',
    projectId: 'fir-flutter-83655',
    storageBucket: 'fir-flutter-83655.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4cWVPJQc65axUBvzmf0sAijtzRoi6EQY',
    appId: '1:660366217495:ios:ba2d353ee3a7afb1ef6752',
    messagingSenderId: '660366217495',
    projectId: 'fir-flutter-83655',
    storageBucket: 'fir-flutter-83655.appspot.com',
    iosBundleId: 'com.example.demoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4cWVPJQc65axUBvzmf0sAijtzRoi6EQY',
    appId: '1:660366217495:ios:03c9c4d1ed276272ef6752',
    messagingSenderId: '660366217495',
    projectId: 'fir-flutter-83655',
    storageBucket: 'fir-flutter-83655.appspot.com',
    iosBundleId: 'com.example.demoFlutter.RunnerTests',
  );
}
